import re

path = "C:/Users/drago/outboundsolved-site/hub.html"
content = open(path, "r", encoding="utf-8").read()

# Find the AI Sequence Generator product card and replace
# Use regex to match the whole card div
pattern = re.compile(
    r'<div class="product-card coming-soon">\s*'
    r'<div class="product-image"[^>]*>🤖</div>\s*'
    r'<span class="badge badge-soon">Coming soon</span>\s*'
    r'<h3>AI Cold Email Sequence Generator</h3>.*?</div>\s*</div>',
    re.DOTALL
)

new_card = '''<div class="product-card">
        <div class="product-image" style="margin-bottom:var(--sp-4)">🤖</div>
        <span class="badge badge-live">Live</span>
        <h3>AI Cold Email Sequence Generator</h3>
        <p class="desc">Enter your offer, get a custom 4-email sequence generated by AI. Personalized to your ICP, your tone, your value prop. Delivered in 60 seconds.</p>
        <div class="price">$19 <small>one-time</small></div>
        <a href="https://buy.stripe.com/6oU4gA5lkgKTdgs2MD6oo04" class="btn">Get this tool →</a>
      </div>'''

match = pattern.search(content)
if match:
    content = content[:match.start()] + new_card + content[match.end():]
    open(path, "w", encoding="utf-8").write(content)
    print("✓ Product 2 card updated to Live")
    print(f"  Replaced {len(match.group())} chars with {len(new_card)} chars")
else:
    print("✗ Could not find the card. Checking what exists...")
    if "AI Cold Email Sequence Generator" in content:
        idx = content.find("AI Cold Email Sequence Generator")
        print("Found 'AI Cold Email Sequence Generator' at index", idx)
        # Show 800 chars around it
        snippet = content[max(0,idx-400):idx+600]
        print(snippet)